[mqtt_broker]
host = "localhost"
port = "1883"
vda_interface = "uagv"
username = ""
password = ""

[vehicle]
serial_number = "Vehicle_2"
manufacturer = "skwqy"
vda_version = "v2"
vda_full_version = "2.0.0"

[settings]
map_id = "webots"
state_frequency = 1
visualization_frequency = 1
action_time = 1.0
robot_count = 1
speed = 0.05
